# Generated by Django 5.1.2 on 2024-10-29 04:10

import django.db.models.deletion
import mi_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_cancion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cancion', models.CharField(max_length=100)),
                ('nombre_autor', models.CharField(max_length=100)),
                ('audio', models.FileField(blank=True, upload_to='static/archivos_proyecto/audios/', validators=[mi_app.models.validar_audio])),
                ('imagen', models.ImageField(blank=True, upload_to='static/archivos_proyecto/imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lista', models.CharField(max_length=100)),
                ('descripcion_lista', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogos', to='mi_app.cancion')),
            ],
        ),
        migrations.CreateModel(
            name='Cola',
            fields=[
                ('id_cola', models.AutoField(primary_key=True, serialize=False)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colas', to='mi_app.catalogo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colas', to='mi_app.lista')),
            ],
        ),
        migrations.CreateModel(
            name='PreLista',
            fields=[
                ('id_prelista', models.AutoField(primary_key=True, serialize=False)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prelistas', to='mi_app.catalogo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prelistas', to='mi_app.lista')),
            ],
        ),
    ]
